### ISSUE TITLE
traning cost of DMCP training, Pruned Model Sampling, fine-tuning

### ISSUE THREAD

**Issue by he-y** [Zx55/dmcp#10]
Thanks for your great work!
Could you please provide the traning cost of DMCP training, Pruned Model Sampling, fine-tuning?
How many hours needed for these steps?
Thanks!

**Comment by cardwing** [comment]
In their paper, they mentioned that it took 40 epochs and 100 epochs for the DMCP training and pruned network training (250 epochs for MobileNetV2), respectively. The cost of the pruned model sampling can be neglected if using expected sampling since it only needs to calculate the expected channel numbers in each layer and the pruning process is unique. If you want to calculate the exact training hours and compare your algorithm with DMCP regarding this perspective, it seems that you need to keep all factors to be the same, e.g., GPU type, whether using distributed training, batch size, etc.

**Comment by Zx55** [comment]
For reference, we prune the **ResNet50 (flops 2200)** and retrain it from scratch on the **ImageNet** using **32 1080TIs**:
|stage|estimated time|
|:----:|:----:|
|dmcp training|8h(using stage1 checkpoint) ~ 15h|
|fine-tuning|24h|

**Comment by he-y** [comment]
Thanks for the reply.
